import "./Logo.css";

/**
 * The college seal, used everywhere the site brands itself — navbar, footer,
 * login card and both portal sidebars.
 *
 * One component so the path, the alt text and the circular crop are decided
 * once. The artwork is generated by `npm run optimize:logo`; never point this
 * at the full-size original in `_original-photos/`.
 */
export default function Logo({ size = 24, className = "" }) {
  return (
    <img
      src="/logo.png"
      alt="Community Model Girls College"
      width={size}
      height={size}
      className={`logo ${className}`.trim()}
      decoding="async"
    />
  );
}
